config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :media
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    # if user.admin?
    #   can :manage, :all
    # else
    #   can :read, :all
    # end

    can :manage, Medium, user_id: user.id
  end

  # def quest(user)
  #
  # end


  #
  # The first argument to `can` is the action you are giving the user
  # permission to do.
  # If you pass :manage it will apply to every action. Other common actions
  # here are :read, :create, :update and :destroy.
  #
  # The second argument is the resource the user can perform the action on.
  # If you pass :all it will apply to every resource. Otherwise pass a Ruby
  # class of the resource.
  #
  # The third argument is an optional hash of conditions to further filter the
  # objects.
  # For example, here the user can only update published articles.
  #
  #   can :update, Article, :published => true
  #
  # See the wiki for details:
  # https://github.com/ryanb/cancan/wiki/Defining-Abilities


end

app/models/concerns/media_type.rb
module MediaType
  extend ActiveSupport::Concern
  included do
    has_many :media, as: :resource, dependent: :destroy
  end

  module ClassMethods
    def get_instance(params)
      new(params)
    end
  end
end

app/models/media_types/link.rb
module MediaTypes
  class Link < ActiveRecord::Base
    include MediaType

    validates_presence_of :url

    def self.get_instance(params)
      if params[:url].present?
        find_by(url: params[:url]) || new(params)
      else
        new(params)
      end
    end
  end
end

app/models/medium.rb
class Medium < ActiveRecord::Base
  belongs_to :resource, polymorphic: true
  belongs_to :user
  accepts_nested_attributes_for :resource
  after_destroy :destroy_resource

  validates_presence_of :name

  private

  def destroy_resource
    resource.destroy if resource.media.length == 0
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :media


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user.present?
      user_home
    else
      guest_home
    end
  end

  def guest_home
    render :guest_home
  end

  def user_home
    render :user_home
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  load_and_authorize_resource except: [:create]

  def new
    @medium = Medium.new
    resource_class = "MediaTypes::#{params[:type].camelize}".constantize
    @medium.resource = resource_class.new
  end

  def create
    @medium = Medium.new(medium_params)
    @medium.user = current_user
    authorize! :create, @medium
    resource_class = "MediaTypes::#{params[:resource][:type].camelize}".constantize
    @medium.resource = resource_class.get_instance(resource_params)
    if @medium.save
      render :edit
    else
      render :new
    end
  end

  def update
    @medium.update_attributes(medium_params)
    render :edit
  end

  def index
    @media = current_user.media
  end

  def destroy
    @medium.destroy
    redirect_to action: :index
  end

  private

  def medium_params
    params.require(:medium).permit(:name,:description)
  end

  def resource_params
    params.require(:medium).permit(resource_attributes:[:url])[:resource_attributes]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/guest_home.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <p>It's best of the best of media gallery</p>

  </div>
</div>

app/views/home/user_home.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <p>It's best of the best of media gallery1</p>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple media gallery</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Simple media gallery</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li class="navbar-text">Hello, <%=current_user.email%>!</li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete%></li>
      <% else %>
          <li class="navbar-text">Hello, Guest!</li>
          <li class="<%=(request.path == new_user_session_path ? 'active' : '')%>">  <%= link_to 'Sign in', new_user_session_path%></li>
          <li class="<%=(request.path == new_user_registration_path ? 'active' : '')%>"> <%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
  <!--/.nav-collapse -->
  </div>
</nav>
<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name.to_sym == :error ? "danger" : "success" } alert-dismissable" do %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= msg %>
      <% end %>
  <% end %>
  <%= yield %>
</div>

<!-- /container -->
</body>
</html>

app/views/media/_form.html.erb
<% url = @medium.new_record? ? media_path : medium_path(@medium) %>
<%= simple_form_for(@medium, as: :medium, url: url) do |f| %>
    <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.simple_fields_for :resource, @medium.resource do |resource_fields| %>
        <% resource_type = resource_fields.object.class.name.demodulize.downcase%>
        <% if f.object.new_record? %>
            <%= hidden_field_tag 'resource[type]', resource_type %>
        <% end %>
        <%= render partial: "media/types/#{resource_type}/fields", locals: {form: f, fields: resource_fields} %>
    <% end %>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/media/edit.html.erb
<%=render partial: 'form'%>

app/views/media/index.html.erb
<% %w(link image).each do |type| %>
    <%= link_to "New #{type}", new_medium_path(type: type), class: 'btn btn-default'%>
<% end %>
<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Content</th>
    <th></th>
  </tr>

  </thead>
  <tbody>
  <% @media.each do |medium| %>
      <tr>
        <td><%= medium.name %></td>
        <td><%= medium.description %></td>
        <td>

          <%= case medium.resource_type
                when MediaTypes::Link.name
                  link_to(medium.resource.url)
              end %>
        </td>
        <td>
          <%= link_to 'Edit', edit_medium_path(medium) %>
          <%= link_to 'Delete', medium_path(medium), method: :delete %>
        </td>
      </tr>
  <% end %>

  </tbody>


</table>

app/views/media/new.html.erb
<%=render partial: 'form'%>

app/views/media/types/link/_fields.html.erb
<%=fields.input :url, disabled: !form.object.new_record?%>